name: haskell-nfc
version: 0.1.0.0
github: "satosystems/haskell-nfc"
license: BSD3
author: "Satoshi Ogata"
maintainer: "satosystems@gmail.com"
copyright: "(c) 2021 Satoshi Ogata"

extra-source-files:
  - README.md
  - ChangeLog.md

description: Please see the README on GitHub at <https://github.com/satosystems/haskell-nfc#readme>

dependencies:
  - base >= 4.7 && < 5
  - directory
  - filepath
  - text
  - unicode-transforms

library:
  source-dirs: src

executables:
  haskell-nfc:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-nfc

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-nfc
